[colors]
foreground    = "#634D36"
background    = "#F7F2ED"
cursor_bg     = "#634D36"
cursor_border = "#634D36"
cursor_fg     = "#F7F2ED"
selection_bg  = "#E0CCB8"
selection_fg  = "#634D36"
ansi = ["#F0E6DB","#D65C5C","#7AB87A","#D99D26","#708BC2","#C99CC9","#85ADAD","#634D36"]
brights = ["#E0CCB8","#AD1F1F","#559933","#D99D26","#708BC2","#B34D90","#366363","#634D36"]
